// Code generated by goctl. DO NOT EDIT.
package types

type PingReq struct {
	Name string `path:"name"`
}

type PingData struct {
	Name string `json:"name"`
}

type PingResp struct {
	CommonResp
	Data PingData `json:"data"`
}

type AuthReq struct {
	Username string `json:"username"`
}

type AuthData struct {
	Token string `json:"token"`
}

type AuthResp struct {
	CommonResp
	Data AuthData `json:"data"`
}

type RespTemplate struct {
	Code int32       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type CommonResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}
