// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	svc1 "app/internal/handler/svc1"
	"app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping/:name",
				Handler: svc1.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: svc1.AuthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/svc1"),
	)
}
